# Security configuration for Symfony
security:
    # Password hashers configuration
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # User provider configuration
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        # Development firewall (disable security for dev environment)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login
            stateless: true

        # Main firewall (you can define your authentication methods here)
        main:
            lazy: true
            provider: app_user_provider
            # You can enable different ways to authenticate here:
            # Example: form_login, http_basic, jwt, etc.

            # Uncomment and configure these as needed:
            # form_login: ~
            # http_basic: ~
            # json_login: ~
            # jwt: ~   # Enable if using JWT authentication (LexikJWTAuthenticationBundle)
            
            # Security access control for specific routes
            # access_control:
            #     - { path: ^/admin, roles: ROLE_ADMIN }
            #     - { path: ^/profile, roles: ROLE_USER }

    # Access control (optional)
    # This section allows you to define rules to restrict access based on user roles.
    # Uncomment and modify to restrict access to parts of your application.
    # access_control:
    #     - { path: ^/admin, roles: ROLE_ADMIN }
    #     - { path: ^/profile, roles: ROLE_USER }

# Security configuration for the test environment (optional)
# Uncomment this section if you want to adjust password hashing settings for tests
# when@test:
#     security:
#         password_hashers:
#             # In test environments, reduce password hashing time for faster tests
#             Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
#                 algorithm: auto
#                 cost: 4
#                 time_cost: 3
#                 memory_cost: 10

